apiVersion: apps/v1
kind: Deployment
metadata:
  name: instabug-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
          app: instabug
  template:
    metadata:
      labels:
          app: instabug
    spec:
      containers:
        - name: instabug-container
          image: nouranahmed5/instabug-app-task:2
          env:
             - name: MYSQL_HOST
               value: "db"
             - name: MYSQL_USER
               value: "root"
             - name: MYSQL_PASS
               value: "nouran"
             - name: MYSQL_PORT
               value: "3306"        
---
apiVersion: v1
kind: Service
metadata:
  name: instabug-service
spec:
  selector:
    app: instabug
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: instabug-ingress
  labels:
    name: instabug
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: instabug-service
            port: 
              number: 80
