---
apiVersion: v1
kind: Service
metadata:
  name: instabug-service
spec:
  selector:
    app: instabug
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 9090 }}
      targetPort: {{ .Values.service.port | default 9090 }}